import type { NextPage } from "next";
import Head from "next/head";
import CalculationPage from "./calculate/CalculationPage";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Happy House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CalculationPage />
    </div>
  );
};

export default Home;
